---
assembly_info:
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  assembly_version: "{version}"
  file: "**\\AssemblyInfo.*"
  patch: true
install:
  # Download .NET Core 2.0 Preview 3 SDK and add to PATH
  - ps: $urlCurrent = "https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview3-006857/dotnet-sdk-2.0.0-preview3-006857-win-x64.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFileCurrent = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), [System.IO.Path]::GetRandomFileName())
  - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
branches:
  only:
    - master
build:
  publish_nuget: true
  verbosity: minimal
before_build:
  - nuget restore
configuration: Release
environment:
  AppVeyorAPIToken:
    secure: GvygCCndEp8eiXvItooIyglWYnyfUvg4YNyaufw3N3A=
  AppVeyorGlobalAPIToken:
    secure: XaWtuymf7dtXgjvEdnxXZVuIGVwMYUqOcE3dl3f3JzA=
  NugetAPIToken:
    secure: U630adFlFmWqwvorvfwA+YvFtAkfL+vw1EX0vCXbyk+R6qiLkIeqKek9yK+poBjV
image: "Visual Studio 2017"
nuget:
  disable_publish_on_pr: true
on_success:
  -
    ps: |
        if ( $env:APPVEYOR_REPO_TAG -And `
            ($env:APPVEYOR_REPO_TAG_NAME -match '^v\d+\.\d+\.\d+$') -And `
            ($env:APPVEYOR_REPO_BRANCH -eq 'master') -And `
            ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null) ) # new version release
        {
          Write-Host "Pushing ${env:APPVEYOR_REPO_TAG_NAME} to NuGet feed"

          & "nuget" @("setApiKey", $env:NugetAPIToken)

          Get-ChildItem .\*.nupkg `
          | % { & "nuget" @("push", $_.FullName, `
                            "-Source", "https://www.nuget.org/api/v2/package") }
        }

        rm .\*.nupkg
version: "0.1.0.{build}"
