---
assembly_info:
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  assembly_version: "{version}"
  file: "**\\AssemblyInfo.*"
  patch: true
branches:
  only:
    - master
build:
  publish_nuget: true
  verbosity: minimal
configuration: Release
environment:
  AppVeyorAPIToken:
    secure: GvygCCndEp8eiXvItooIyglWYnyfUvg4YNyaufw3N3A=
  AppVeyorGlobalAPIToken:
    secure: XaWtuymf7dtXgjvEdnxXZVuIGVwMYUqOcE3dl3f3JzA=
  NugetAPIToken:
    secure: U630adFlFmWqwvorvfwA+YvFtAkfL+vw1EX0vCXbyk+R6qiLkIeqKek9yK+poBjV
image: "Visual Studio 2017"
init:
  -
    ps: |
        if ( $env:APPVEYOR_REPO_TAG -And `
            ($env:APPVEYOR_REPO_TAG_NAME -match '^v\d+\.\d+\.\d+$') -And `
            ($env:APPVEYOR_REPO_BRANCH -eq 'master') -And `
            ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null) )
        {
          Write-Host "Updating the build version to ${env:APPVEYOR_REPO_TAG_NAME}"

          $vf = $env:APPVEYOR_REPO_TAG_NAME
          $vf = $vf -replace '^v',''
          $vf = $vf + ".{build}"

          $YAML = `
             Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/projects/bazzilic/BigIntegerExt/settings/yaml' `
                               -Headers @{ "Authorization" = "Bearer ${env:AppVeyorAPIToken}" ;  "Content-type" = "plain/text" } `
                               -Method Get

          $YAML = $YAML -replace '^version: \d+.\d+.\d.{build}', "version: $vf"

          Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/projects/bazzilic/BigIntegerExt/settings/yaml' `
                            -Headers @{ "Authorization" = "Bearer ${env:AppVeyorAPIToken}" ;  "Content-type" = "application/json" } `
                            -Method Put `
                            -Body $YAML

          Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/projects/bazzilic/BigIntegerExt/settings/build-number' `
                            -Headers @{ "Authorization" = "Bearer ${env:AppVeyorAPIToken}" ;  "Content-type" = "application/json" } `
                            -Method Put `
                            -Body '{ nextBuildNumber: 1 }'

          $curver = $vf -replace '{build}','0'

          Update-AppVeyorBuild -Version $curver
        }
nuget:
  disable_publish_on_pr: true
on_success:
  -
    ps: |
        if ( $env:APPVEYOR_REPO_TAG -And `
            ($env:APPVEYOR_REPO_TAG_NAME -match '^v\d+\.\d+\.\d+$') -And `
            ($env:APPVEYOR_REPO_BRANCH -eq 'master') -And `
            ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null) ) # new version release
        {
          Write-Host "Pushing ${env:APPVEYOR_REPO_TAG_NAME} to NuGet feed"

          & "nuget" @("setApiKey", $env:NugetAPIToken)

          Get-ChildItem .\*.nupkg `
          | % { & "nuget" @("push", $_.FullName, `
                            "-Source", "https://www.nuget.org/api/v2/package") }
        }

        rm .\*.nupkg
version: "1.0.7.{build}"
